version: "3.9"

services:
  backend:
    build: ./server
    ports:
      - "8081:8081"
    environment:
      ENV: ${ENV}
      CLIENT_IP: ${CLIENT_IP}
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET} 
  frontend:
    build: ./web
    ports:
      - "3000:80"
    environment:
      BACKEND_URL: http://localhost:8081
    depends_on:
      - backend